name: tech_goal
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.13.0
  mask_text_input_formatter: ^2.5.0
  image_picker: ^1.0.4
  math_expressions: ^2.4.0
  geolocator: ^10.1.0
  flutter_spinkit: ^5.2.0
  dio: ^5.3.3




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/images/
